[build]
target = "../targets/kernel.json"

[target.'cfg(target_os = "none")']
runner = "../scripts/run-qemu.sh"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]