[workspace]
default-members = [
    "kernel",
]
members = [
    "bootloader",
    "kernel",
    "modules/test_module"
]

resolver = "2"

[workspace.dependencies]
test_module = { path = "modules/test_module" }
